#!/bin/bash
# Installs fvi
#
# Requires Python3.5.
#
# This install script installs into ~/.local. It also installs the manpage into 
# ~/.local/man.  This is done with the hack below because setuptools can no 
# longer install manpages.  Be sure to add ~/.local/bin into your path.
#
# Rather than installing with this script, you can also install using:
#    pip3 install fvi
# but in this case you need to copy the man page manually. If you install into 
# ../bin/fvi, then you should put the man page to ../man/man1/fvi.1.

cmd=fvi

# Set python to the version of python you wish to use (ex. python2 or python3)
python=python3

# run pylint to find egregious errors
# this is optional, you can delete this line if you don't have pylint
# pylint -E --disable=no-member $cmd

# Determine the version of python we are using
vers=$($python -c 'import sys; print("%s.%s" % (sys.version_info[0], sys.version_info[1]))')
echo "Installing $cmd to ~/.home/bin (Python$vers)."

# remove build directories from a previous install to assure a clean install
rm -rf build dist $cmd.egg-info install.out

# install $cmd
python$vers setup.py install --quiet --user >& install.out
if [[ $? -ne 0 ]] ; then
    echo "Problems found, aborting (see install.out)"
    exit 1
fi

# setuptools no longer installs man pages properly, so I must fix things up
for sect in 1
do
    mkdir -p ~/.local/man/man$sect
    rm -f ~/.local/man/man$sect/$cmd.$sect
    ln -s ~/.local/lib/python$vers/site-packages/$cmd-*.egg/man/man$sect/$cmd.$sect ~/.local/man/man$sect
done

# remove build directories, because I like a clean directory
rm -rf build dist $cmd.egg-info
